list: $/vdlp/basicauthentication/models/excludedurl/columns.yaml
modelClass: Vdlp\BasicAuthentication\Models\ExcludedUrl
title: vdlp.basicauthentication::lang.excludedurls.list.title
recordUrl: vdlp/basicauthentication/excludedurls/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_prompt
