name: vdlp.basicauthentication::lang.excludedurls.form.record_name_singular
form: $/vdlp/basicauthentication/models/excludedurl/fields.yaml
modelClass: Vdlp\BasicAuthentication\Models\ExcludedUrl
defaultRedirect: vdlp/basicauthentication/excludedurls

create:
    title: vdlp.basicauthentication::lang.excludedurls.form.create_title
    redirect: vdlp/basicauthentication/excludedurls/update/:id
    redirectClose: vdlp/basicauthentication/excludedurls

update:
    title: vdlp.basicauthentication::lang.excludedurls.form.edit_title
    redirect: vdlp/basicauthentication/excludedurls
    redirectClose: vdlp/basicauthentication/excludedurls
