name: vdlp.basicauthentication::lang.credentials.form.record_name_singular
form: $/vdlp/basicauthentication/models/credential/fields.yaml
modelClass: Vdlp\BasicAuthentication\Models\Credential
defaultRedirect: vdlp/basicauthentication/credentials

create:
    title: vdlp.basicauthentication::lang.credentials.form.create_title
    redirect: vdlp/basicauthentication/credentials/update/:id
    redirectClose: vdlp/basicauthentication/credentials

update:
    title: vdlp.basicauthentication::lang.credentials.form.edit_title
    redirect: vdlp/basicauthentication/credentials
    redirectClose: vdlp/basicauthentication/credentials
