list: $/vdlp/basicauthentication/models/credential/columns.yaml
modelClass: Vdlp\BasicAuthentication\Models\Credential
title: vdlp.basicauthentication::lang.credentials.list.title
recordUrl: vdlp/basicauthentication/credentials/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_prompt
